- hosts: localhost
  gather_facts: False

  tasks:
    - name: create backup dir
      file: path=~/.backup state=directory
    - name: link all files
      file: src={{ item }} dest=~/.{{ item|basename }} state=link
      with_fileglob:
        - ~/dotfiles/*
      when:
        - item|basename != "init.sh"
        - item|basename != "playbook.yml"
        - item|basename != "README.md"
    - name: install required packages
      sudo: True
      pacman: name={{ item }} state=present update_cache=yes
      with_items:
        - zsh
        - grml-zsh-config
        - gvim
        - ctags
        - tmux
        - git
        - htop
        - dstat
        - the_silver_searcher
