#!/bin/bash

if [ "$(pidof spotify)" ]
then
    WINID=`xdotool search --class spotify | tail -n1`
    case $BLOCK_BUTTON in
        1) playerctl play-pause &> /dev/null && pkill -SIGRTMIN+2 i3blocks ;;
        2) playerctl play-pause &> /dev/null && pkill -SIGRTMIN+2 i3blocks ;;
        3) playerctl play-pause &> /dev/null && pkill -SIGRTMIN+2 i3blocks ;;
        4) playerctl previous &> /dev/null && sleep 0.1 && pkill -SIGRTMIN+2 i3blocks ;;
        5) playerctl next &> /dev/null && sleep 0.1 && pkill -SIGRTMIN+2 i3blocks ;;
    esac

    if [[ $(xdotool getwindowname ${WINID}) = "Spotify" ]]
    then
        echo " paused" && echo && echo '#458588';
    else
        echo  $(xdotool getwindowname ${WINID})
    fi
else
    echo " stopped" && echo && echo '#458588';
fi

