#!/usr/bin/fish

set percent (top -bn1 | sed -n '/Cpu/p' | awk '{print $2}' | sed 's/..,//')

echo "$percent%"
echo "$percent%"

if test $percent -gt 80
    echo "#fb4934"
else if test $percent -gt 50
    echo "#d79921";
end
