#!/usr/bin/fish

set text (free -mh --si | grep Mem: | column -to" " | cut -d" " -f7)
echo $text

set avail (free -m | grep Mem: | column -to" " | cut -d" " -f7)

# this would be proper, but why bother?
# set total (free -m | grep Mem: | column -to" " | cut -d" " -f2)
# set warn_bound (math "$total * 0.1")
set warn_bound 1200

if test $avail -lt $warn_bound
    echo "#fb4934"
end
