#!/bin/fish

if set -q BLOCK_BUTTON
    switch $BLOCK_BUTTON
        case 1
            pavucontrol
        case 3
            pactl set-sink-mute alsa_output.pci-0000_00_1f.3.analog-stereo toggle
        case 4
            pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo +1%
        case 5
            pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo -1%
    end
end

set mute (pactl list sinks | grep "Mute: " | cut -d: -f 2 | tr -d [:blank:])

if [ $mute = "no" ]
    echo  (pactl list sinks | grep "Volume: f" | cut -d'/' -f2 | tr -d [:blank:])
else if [ $mute = "yes" ]
    echo ' 0%' && echo && echo '#458588'
end
