[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "<span font='15'></span>"

[icons]
name = "awesome"
[icons.overrides]
time = " "

[[block]]
block = "networkmanager"

[[block]]
block = "toggle"
text = "BelWü"
command_state = "netctl status belwue_openconnect | grep ' active'"
command_on = "sudo netctl start belwue_openconnect"
command_off = "sudo netctl stop belwue_openconnect"
interval = 5

[[block]]
block = "toggle"
text = "BelWü split"
command_state = "netctl status belwue_openconnect_split | grep ' active'"
command_on = "sudo netctl start belwue_openconnect_split"
command_off = "sudo netctl stop belwue_openconnect_split"
interval = 5

[[block]]
block = "toggle"
text = "BW ovpn udp"
command_state = "nmcli c s belwue-udp | grep connected"
command_on = "nmcli c u belwue-udp"
command_off = "nmcli c d belwue-udp"
interval = 5

[[block]]
block = "toggle"
text = "BW ovpn tcp"
command_state = "nmcli c s belwue-tcp | grep connected"
command_on = "nmcli c u belwue-tcp"
command_off = "nmcli c d belwue-tcp"
interval = 5

[[block]]
block = "toggle"
text = "UUlm openconnect"
command_state = "netctl status uulm_openconnect | grep ' active'"
command_on = "sudo netctl start uulm_openconnect"
command_off = "sudo netctl stop uulm_openconnect"
interval = 5
