[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "<span font='15'></span>"

[icons]
name = "awesome"
[icons.overrides]
time = " "

[[block]]
block = "cpu"
interval = 1
info=80
warning=90
critical=95

[[block]]
block = "load"
interval = 1
format = "{1m}"
info=3.5
warning=4
critical=5

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{average}"
chip = "coretemp-isa-0000"
idle = 60

[[block]]
block = "memory"
display_type = "memory"
clickable = false
format_mem = "{mem_used_percents}"
warning_mem=85
critical_mem=90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "backlight"

[[block]]
block = "sound"
on_click = "swaymsg -q -- exec pavucontrol"
#show_volume_when_muted = true

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"

[[block]]
block = "battery"
device = "BAT0"
interval = 10
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
