[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "<span font='15'></span>"

[icons]
name = "awesome"
[icons.overrides]
time = " "

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
