[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "<span font='15'></span>"

[icons]
name = "awesome"
[icons.overrides]

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{average}°"
chip = "coretemp-isa-0000"
idle = 50

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mupi}%"
clickable = false

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "backlight"

[[block]]
block = "sound"
on_click = "swaymsg -q -- exec pavucontrol"
#show_volume_when_muted = true

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
on_collapsed_click = "spotify"
max_width = 30
marquee_speed = 0.2
marquee_interval = 5

[[block]]
block = "battery"
device = "BAT1"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
